project:
  type: website
  output-dir: "."

website:
  title: "Higor Palote Volpi"
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: Projetos
        href: projects.html

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



